version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '33066:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'rootuser'
       MYSQL_PASSWORD: 'password123'
       MYSQL_ROOT_PASSWORD: 'password123456'
    volumes:
      - .dbdata:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db